apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: joseguachun/clasificacion_ftb:latest
        command: ["/bin/sh", "-c"] # Cambia el command para usar un shell
        args: ["sleep 10 && python manage.py runserver 0.0.0.0:8000"] # Añade un sleep de 10 segundos
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_HOST
          value: postgres-service
        - name: ALLOWED_IP
          value: 3.226.245.96
